// Array of dad jokes
const jokes = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm afraid for the calendar. Its days are numbered.",
    "What do you call fake spaghetti? An impasta.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "Why can't your nose be 12 inches long? Because then it would be a foot.",
    "How do you organize a space party? You planet.",
    "Why did the math book look sad? Because it had too many problems.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why can't you give Elsa a balloon? Because she’ll let it go.",
    "Why was the math book so stressed? It had too many problems.",
    "Why do cows wear bells? Because their horns don’t work.",
    "Why did the bicycle fall over? Because it was two tired.",
    "What do you call a fish with no eyes? Fsh.",
    "What do you call a can opener that doesn’t work? A can’t opener.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why did the cookie go to the doctor? Because it was feeling crumby.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why are elevator jokes so good? They work on many levels.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, they’d be bagels.",
    "What do you call an alligator in a vest? An investigator.",
    "How does a penguin build its house? Igloos it together.",
    "What did the fisherman say to the magician? Pick a cod, any cod!",
    "Why don’t skeletons ever trick or treat? They don’t have the guts.",
    "What do you call a pig that does karate? A pork chop.",
    "Why did the photo go to jail? It was framed.",
    "What kind of music do mummies listen to? Wrap music.",
    "Why couldn’t the bicycle stand up by itself? It was two tired.",
    "Why was the broom late? It swept in.",
    "Why are ghosts bad liars? Because you can see right through them.",
    "Why did the computer go to the doctor? It caught a virus.",
    "What do you call a dog magician? A labracadabrador.",
    "Why don’t ants get sick? Because they have tiny ant-bodies.",
    "What kind of car does a sheep drive? A lamborghini.",
    "Why did the skeleton go to the party alone? He had no body to go with him.",
    "What did the big flower say to the little flower? Hi, bud!",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "What do you call a belt made of watches? A waist of time.",
    "Why don’t oysters donate to charity? Because they’re shellfish.",
    "Why did the scarecrow become a successful businessman? Because he was outstanding in his field.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine.",
    "What’s brown and sticky? A stick.",
    "Why don’t scientists trust stairs? They’re always up to something.",
    "What did one hat say to the other? You stay here, I’ll go on ahead.",
    "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
    "Why did the chicken cross the playground? To get to the other slide.",
    "What’s orange and sounds like a parrot? A carrot.",
    "What do you get when you cross a snowman with a vampire? Frostbite.",
    "Why did the fisherman get bad grades? Because his grades were below sea level.",
    "Why don’t basketball players go on vacation? They’d get called for traveling.",
    "What did the cowboy say at his second rodeo? This ain’t my first rodeo!",
    "Why can’t your hand be 12 inches long? Because then it’d be a foot.",
    "Why don’t dinosaurs drive cars? Because they’re extinct!",
    "Why was the stadium so hot after the game? All the fans left.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "What do you call a lazy kangaroo? A pouch potato.",
    "Why was the baby strawberry crying? Because its parents were in a jam.",
    "What’s a pirate’s favorite letter? You’d think it’s R, but it’s actually the C.",
    "What do you call a group of musical whales? An orca-stra.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why don’t elephants use computers? They’re afraid of the mouse.",
    "What do you call a boomerang that doesn’t come back? A stick.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "Why did the banker switch careers? He lost interest.",
    "Why did the coffee file a police report? It got mugged.",
    "What do you call two birds in love? Tweethearts.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "Why can’t skeletons play church music? Because they don’t have organs.",
    "Why do vampires always seem sick? Because they’re always coffin.",
    "Why did the bullet lose its job? It got fired.",
    "Why don’t fish play basketball? Because they’re afraid of the net.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "Why did the melon jump into the lake? Because it wanted to be a watermelon.",
    "What did the clock do when it got hungry? It went back four seconds.",
    "Why can’t you hear a pterodactyl in the bathroom? Because the P is silent.",
    "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
    "Why did the golfer bring extra pants? In case he got a hole in one.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What kind of tea is hard to swallow? Reality.",
    "What’s a computer’s favorite snack? Microchips.",
    "Why can’t you trust an atom? Because they make up everything.",
    "Why do bananas use sunscreen? Because they peel.",
    "Why did the student eat his homework? Because the teacher said it was a piece of cake."
];

function showJoke() {
    const randomIndex = Math.floor(Math.random() * jokes.length);
    const jokeElement = document.getElementById('joke');
    jokeElement.textContent = jokes[randomIndex];
}
